//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Content { get; set; }
        public Nullable<int> AnswerBy { get; set; }
        public Nullable<System.DateTime> AnswerAt { get; set; }
        public int Likes { get; set; }
        public bool Accepted { get; set; }
        public int Unlikes { get; set; }
    
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
    }
}
