//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public int Hits { get; set; }
        public System.DateTime LastAskedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
