//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Categories = new HashSet<Category>();
            this.HotWords = new HashSet<HotWord>();
            this.Knowledges = new HashSet<Knowledge>();
            this.Logs = new HashSet<Log>();
            this.Questions = new HashSet<Question>();
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string RealName { get; set; }
        public bool Locked { get; set; }
        public string Email { get; set; }
        public int Score { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<HotWord> HotWords { get; set; }
        public virtual ICollection<Knowledge> Knowledges { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
